language: csharp
solution: LuasTimes.sln

before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore LuasTimes.sln
after_script:
  - nunit-console LuasTimes/bin/Release/LuasTimes.dll