//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuasTimes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LuasTimes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luas Info.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EndOfServices_Reprompt {
            get {
                return ResourceManager.GetString("EndOfServices_Reprompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can ask questions such as, what\&apos;s the recipe, or, you can say exit...Now, what can I help you with?.
        /// </summary>
        internal static string Help_Message {
            get {
                return ResourceManager.GetString("Help_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can say things like, what\&apos;s the recipe, or you can say exit...Now, what can I help you with?.
        /// </summary>
        internal static string Help_Reprompt {
            get {
                return ResourceManager.GetString("Help_Reprompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inbound.
        /// </summary>
        internal static string Inbound {
            get {
                return ResourceManager.GetString("Inbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luas.
        /// </summary>
        internal static string Luas {
            get {
                return ResourceManager.GetString("Luas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;phoneme alphabet=&quot;ipa&quot; ph=&quot;/l̪ˠuəsˠ/&quot;&gt;Luas&lt;/phoneme&gt;.
        /// </summary>
        internal static string Luas_SSML {
            get {
                return ResourceManager.GetString("Luas_SSML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outbound.
        /// </summary>
        internal static string Outbound {
            get {
                return ResourceManager.GetString("Outbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye!.
        /// </summary>
        internal static string StopMessage {
            get {
                return ResourceManager.GetString("StopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next tram from {0} {1} is due now. The following departure is in {2}.
        /// </summary>
        internal static string Time_DueAndNext_1 {
            get {
                return ResourceManager.GetString("Time_DueAndNext_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next &lt;phoneme alphabet=&quot;ipa&quot; ph=&quot;/l̪ˠuəsˠ/&quot;&gt;Luas&lt;/phoneme&gt; from {0} {1} is due now. The following tram is due in {2}. .
        /// </summary>
        internal static string Time_DueAndNext_1_SSML {
            get {
                return ResourceManager.GetString("Time_DueAndNext_1_SSML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next tram from {0} {1} is due now. The following departure is in {2}. .
        /// </summary>
        internal static string Time_DueAndNext_2 {
            get {
                return ResourceManager.GetString("Time_DueAndNext_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        internal static string Time_Minutes_Plural {
            get {
                return ResourceManager.GetString("Time_Minutes_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mins.
        /// </summary>
        internal static string Time_Minutes_Plural_Short {
            get {
                return ResourceManager.GetString("Time_Minutes_Plural_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minute.
        /// </summary>
        internal static string Time_Minutes_Single {
            get {
                return ResourceManager.GetString("Time_Minutes_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} min.
        /// </summary>
        internal static string Time_Minutes_Single_Short {
            get {
                return ResourceManager.GetString("Time_Minutes_Single_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no trams forcast from {0}. .
        /// </summary>
        internal static string Time_NoTramsForcast {
            get {
                return ResourceManager.GetString("Time_NoTramsForcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no {0} trams forcast from {1}. .
        /// </summary>
        internal static string Time_NoTramsForcast_Direction {
            get {
                return ResourceManager.GetString("Time_NoTramsForcast_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no trams to {0} from {1}. However, there is a tram to {2}. .
        /// </summary>
        internal static string Time_NoTramsToDestination {
            get {
                return ResourceManager.GetString("Time_NoTramsToDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next Luas from {0} {1} is in {2}. .
        /// </summary>
        internal static string Time_ResultMinutes_1 {
            get {
                return ResourceManager.GetString("Time_ResultMinutes_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next &lt;phoneme alphabet=&quot;ipa&quot; ph=&quot;/l̪ˠuəsˠ/&quot;&gt;Luas&lt;/phoneme&gt; from {0} {1} is in {2}. .
        /// </summary>
        internal static string Time_ResultMinutes_1_SSML {
            get {
                return ResourceManager.GetString("Time_ResultMinutes_1_SSML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next tram from {0} {1} is in {2}. .
        /// </summary>
        internal static string Time_ResultMinutes_2 {
            get {
                return ResourceManager.GetString("Time_ResultMinutes_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I didn&apos;t understand the stop provided. Ensure you are using a valid stop..
        /// </summary>
        internal static string UnknownStop {
            get {
                return ResourceManager.GetString("UnknownStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I didn&apos;t understand the stop provided. Example stops are St. Stephen&apos;s Green or Abbey Street.
        /// </summary>
        internal static string UnknownStopRepromt {
            get {
                return ResourceManager.GetString("UnknownStopRepromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}. You can ask things like, when is the next Luas from St. Stephen&apos;s Green..
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I didn&apos;t understand the stop provided. Example stops are St. Stephen&apos;s Green or Abbey Street.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For instructions on what you can say, please say help me..
        /// </summary>
        internal static string WelcomeRepromt {
            get {
                return ResourceManager.GetString("WelcomeRepromt", resourceCulture);
            }
        }
    }
}
